"""Added new Table

Revision ID: 15704139bd98
Revises: 6ab904c62d3b
Create Date: 2026-02-05 11:41:12.851380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15704139bd98'
down_revision = '6ab904c62d3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roomuser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room', sa.String(length=10), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('translated_text', sa.String(), nullable=True))
        batch_op.drop_column('text_message')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_message', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('translated_text')

    op.drop_table('roomuser')
    # ### end Alembic commands ###
