"""Changes in DB

Revision ID: 6ab904c62d3b
Revises: 69d071ec4f6a
Create Date: 2026-02-05 02:29:53.742541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ab904c62d3b'
down_revision = '69d071ec4f6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_message', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('text_message', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_column('message')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('timestamp')
        batch_op.drop_column('text_message')
        batch_op.drop_column('audio_message')

    # ### end Alembic commands ###
