"""new migration

Revision ID: b6664f605a07
Revises: 
Create Date: 2026-02-05 19:27:36.314473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6664f605a07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room', sa.String(length=10), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=False),
    sa.Column('audio_message', sa.String(), nullable=True),
    sa.Column('translated_text', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roomuser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room', sa.String(length=10), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roomuser')
    op.drop_table('conversation')
    # ### end Alembic commands ###
